import Razorpay from "razorpay";
import crypto from 'crypto';

const razorpay = new Razorpay({
  key_id: process.env.RAZORPAY_KEY_ID,
  key_secret: process.env.RAZORPAY_KEY_SECRET,
});


/**
 * Creates a Razorpay Order on the server
 * @param {number} amount - Amount in paise (e.g., 50000 for ₹500)
 * @returns {object} Razorpay order object
 */

const createRazorpayOrder = async (amount) => {
    // Note: currency defaults to INR for Indian accounts
    const order = await razorpay.orders.create({
        amount: amount,
        currency: "INR",
        receipt: `receipt_${Date.now()}` // Unique receipt id for your reference
    });

    return order;
};

/**
 * Verifies the payment signature to ensure it wasn't tampered with
 * @param {string} razorpay_order_id 
 * @param {string} razorpay_payment_id 
 * @param {string} razorpay_signature 
 * @returns {boolean}
 */

const verifyPaymentSignature = (razorpay_order_id, razorpay_payment_id, razorpay_signature) => {
   
    
    // Razorpay requires a very specific string format to generate the HMAC
    const expectedSignature = crypto
        .createHmac('sha256', process.env.RAZORPAY_KEY_SECRET)
        .update(`${razorpay_order_id}|${razorpay_payment_id}`)
        .digest('hex');

    // Compare the signature generated by us vs what Razorpay sent
    return expectedSignature === razorpay_signature;
};


export {createRazorpayOrder, verifyPaymentSignature};